services:
  movie-search-engine:
    build: .
    ports:
      - "5005:5000"
    environment:
      - SESSION_SECRET=your-secret-key-change-in-production
      - LOG_LEVEL=INFO
      - ENVIRONMENT=production
      - HOST=0.0.0.0
      - PORT=5000
    volumes:
      - search_index:/app/index
      - movie_data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/status"]  # Обновлен endpoint
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s  # Дать время на инициализацию
    networks:
      - movie-search-network

volumes:
  search_index:
    driver: local
  movie_data:
    driver: local

networks:
  movie-search-network:
    driver: bridge